### ISSUE TITLE
Couldn't load QR login

### ISSUE THREAD

**Issue by trinhcanhphuc** [Ajaxy/telegram-tt#51]
I got this bug when running server, and QR login couldn't show
[2021-07-21T13:31:47.172Z] [ERROR] - [WebSocket connection failed attempt: 6. Cause: Cannot read property 'digest' of undefined]

Cannot read property 'digest' of undefined]

**Comment by shuiRong** [comment]
That's because `window.crypto.subtle.digest`[only works in https.](This feature is available only in secure contexts (HTTPS)).

you must prepare the local https environment like this: ![image](https://user-images.githubusercontent.com/16076993/134035231-1838c67f-228f-4c00-9059-96e4f2a439e7.png)

the keyword is: mkcert, trust root CA, or this Chinese [article](https://juejin.cn/post/6844904116481687565#heading-4)

**Comment by trinhcanhphuc** [comment]
Yes, let me try.

Thanks you very much,
Phuc

Sent with a Spark

**Comment by Ajaxy** [comment]
@trinhcanhphuc Which browser are you on? `localhost` [is considered](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) a secure context too.

**Comment by trinhcanhphuc** [comment]
I was using Microsoft Edge Chromium when I got this bug.

Sent with a Spark

**Comment by Ajaxy** [comment]
Does using Chrome or Safari help?

**Comment by trinhcanhphuc** [comment]
I did not use it, I will check later, thanks a lot

**Comment by Ajaxy** [comment]
Feel free to reopen the issue with more details.
